### ISSUE TITLE
P3 appears to be missing wireframe images

### ISSUE THREAD

**Issue by pjohnmeyer** [PhilosopherKing/liftoff-assignments#3]
The README shows broken image links for me when I view it on GitHub. The "raw" Markdown looks like this:

```
* ![Search WireFrame](file:///C:/Users/Fidget's%20Pass/Downloads/IMG_20180728_222332721.jpg)
* ![Comment WireFrame](IMG_20180728_222351233~2.jpg)
* ![Upload WireFrame](IMG_20180728_222344677~3.jpg)
```

The first one is clearly pointing to a local file; the other two .jpg files are not in the repo as far as I can tell.

**Comment by PhilosopherKing** [comment]
![img_20180728_222344677 3](https://user-images.githubusercontent.com/37670375/43372980-3b862390-936c-11e8-87ec-6d88065dde1b.jpg)
![img_20180728_222332721](https://user-images.githubusercontent.com/37670375/43372981-3e5d0840-936c-11e8-9960-73a964cac725.jpg)
![img_20180728_222351233 2](https://user-images.githubusercontent.com/37670375/43372982-4085e786-936c-11e8-809a-9fe7647e7f40.jpg)
